### ISSUE TITLE
How does this differ?

### ISSUE THREAD

**Issue by nodinosaur** [vrtdev/flutter_adobe#9]
How does this differ from [adobe_mobile_sdk_flutter](https://pub.dev/packages/adobe_mobile_sdk_flutter), (which _is_ endorsed by Adobe)?

From a quick observation they do the same?

**Comment by Kymer** [comment]
The other plugin relies on the older v4 Adobe mobile-services SDK (4.18.9 for [iOS](https://github.com/macif-dev/adobe_mobile_sdk_flutter/blob/master/ios/adobe_mobile_sdk_flutter.podspec) and 4.17.10 for [Android](https://github.com/macif-dev/adobe_mobile_sdk_flutter/blob/master/android/build.gradle)), we rely on the newer (modularised) Adobe Experience Platform Mobile SDKs.

We had already bridged this for our [VRT NWS flutter app](https://medium.com/vrt-digital-studio/porting-the-flemish-news-app-to-flutter-50620453b346) which we recently shipped, and decided to open-source our implementation.

**Comment by nodinosaur** [comment]
Quick question, but seems a reasonable ask to me, what was the reason for not forking & applying these changes to an existing library?

**Comment by nodinosaur** [comment]
Thanks for explaining
